'''
Multi-state Parameter State Value Mappings
'''

import json
from pathlib import Path

from flightdatautilities.patterns import wildcard_match


this_dir = Path(__file__).parent
with open(this_dir / 'validation_tools' / 'list_data' / 'values_mapping.json') as f:
    PARAMETER_CORRECTIONS = json.load(f)

STATE_CORRECTIONS = {
    '': '-',
    '*': '-',
    '.': '-',
    '..': '-',
    '...': '-',
    '....': '-',
    '.....': '-',
    '......': '-',
    '--': '-',
    '---': '-',
    '----': '-',
    '-----': '-',
    '------': '-',
    '-------': '-',
    '--------': '-',
    '---------': '-',
    '----------': '-',
    '<None>': '-',
    'A/P DISC': 'Warning',
    'ABOVE': 'Above',
    'ACTIVATED': 'Active',
    'ACTIVE': 'Active',
    'ACTIVED': 'Active',
    'AIR': 'Air',
    'ALERT': 'Alert',
    'ALERT A': 'Alert',
    'ALL': 'All',
    'ALTITUDE LOST': 'Altitude Lost',
    'ALTN': 'Alternate',
    'AMBER': 'Amber',
    'ANY': 'Any',
    'APPLIED': 'Applied',
    'APPR ENGA': 'Engaged',
    'APU Bleed Valve Fully Open': 'Open',
    'APU Bleed Valve not Fully Open': 'Closed',
    'ARMED': 'Armed',
    'ASYM': 'Assymetrical',
    'AUTO': 'Auto',
    'AUTOMATIC': 'Auto',
    'AVAIL': 'Available',
    'AVAILABLE': 'Available',
    'Actived': 'Activated',
    'Att': 'Attitude',
    'BELOW': 'Below',
    'BETA RANGE': 'Beta',
    'BUS OFF': 'Off',
    'BUS ON': 'On',
    'BYPASS': 'Bypass',
    'CAPABLE': 'Capable',
    'CAPTION OFF': '-',
    'CAPTION ON': 'Engaged',
    'CAUTION': 'Caution',
    'CODED': 'Coded',
    'CLEAR OF CONFLT': 'Clear of Conflict',
    'Cg Warning': 'Warning',
    'CLOSED': 'Closed',
    'CMD Mode': 'Engaged',
    'COMMANDED': 'Deployed',
    'CUTOFF': 'Cutoff',
    'CWS Mode': 'Engaged',
    'DEPLOY': 'Deployed',
    'DEPLOYED': 'Deployed',
    'DETECT': 'Detected',
    'DETECTED': 'Detected',
    'DISABLE': 'Disabled',
    'DISABLED': 'Disabled',
    'DISAGREE': 'Disagree',
    'DISCHARGE': 'Discharge',
    #'DISCONNECT': '-', # Cpnflicting
    'DISCR\'Y': 'Discrepency',
    'DISCONNECT': 'Disconnect',
    'DISENGAGED': '-',
    'DL': 'Down',
    'DISPLAYED': 'Displayed',
    'Diseng': '-',
    'Disp': 'Displayed',
    'Display Off': '-',
    'Display On': 'On',
    'DN+LK': 'Down',
    'DOWN': 'Down',
    'DOWN ADV CORRECT': 'Down Advisory Correct',
    'DOWNLOCKED': 'Down',
    'Down Lock': 'Down',
    'DROP TRACK': 'Drop Track',
    'DUAL': 'Dual',
    'E': 'East',
    'EMIT': 'Keyed',
    'ENABLE': 'Enabled',
    'ENABLED': 'Enabled',
    'ENGA NOT': '-',
    'ENGAGE': 'Engaged',
    'ENGAGED': 'Engaged',
    'EVENT': 'Event',
    'EXTEND': 'Extended',
    'Emitting': 'Keyed',
    'FAIL': 'Fail',
    'FAIL DETEC': 'Fail',
    'FAILURE': 'Fail',
    'FALSE': '-',
    'FAULT': 'Fault',
    'FAULT(S)': 'Fault',
    'FEATHERED': 'Feathered',
    'Falso': '-',
    'Fethr': 'Feathered',
    'FIRE': 'Fire',
    'FLASHED': 'Flashed',
    'FLIGHT': 'Air',
    'FULL EXT': 'Full Extended',
    'FTHRD': 'Feathered',
    'FULL EXT': 'Full Extended',
    'GND': 'Ground',
    'GROUND': 'Ground',
    'HI PRESS': 'High Press',
    'HIGH SPEED': 'High',
    'HIGH TEMP': 'High Temp',
    'HOT': 'Hot',
    'High press': 'High Press',
    'INHIBIT': 'Inhibit',
    'INNER': 'Present',
    'INOP': 'Inoperable',
    'INTRANSIT': 'In Transit',
    'ISOL': 'Isolated',
    'Ignit off': '-',
    'Ignit on': 'On',
    'Inop': 'Inoperable',
    'KEYED': 'Keyed',
    'LEFT': 'Left',
    'LIMIT': 'Limit',
    'LOCKED': 'Locked',
    'LOCKOUT': 'Lockout',
    'LO PRESS': 'Low Press',
    'LOPRESS': 'Low Press',
    'LOPRESS': 'Low Press',
    'LOW PRESS': 'Low Press',
    'LOW SPEED': 'Low',
    'LOW QTY': 'Low',
    'Low Pressure': 'Low Press',
    'LVL CHG': 'Level Change',
    'Low press': 'Low Press',
    'Low prsure': 'Low Press',
    'MACH ENGA': 'Engaged',
    'MAG': 'Magnetic',
    'MAXIMUM': 'Maximum',
    'MMO ENGA': 'Engaged',
    'MID EXT': 'Mid Extended',
    'MIDDLE': 'Present',
    'MODE FAIL': 'Fault',
    'N': 'North',
    'N/UNIQ': '-',
    'NDL': '-',
    'Nfc': 'Not Fully Closed',
    'Nfo': 'Not Fully Open',
    'NO': '-',
    'NO ADVISORY': 'No Advisory',
    'NO COOLING': 'No Cooling',
    'NO DISP': '-',
    'NO INHIBIT': '-',
    'NO RQST': '-',
    'NO FIRE': '-',
    'NO LVL CHG': '-',
    'NO MODE FL': '-',
    'NO SHAKE': '-',
    'NO TEST': '-',
    'NO TRIM': '-',
    'NO WARN': '-',
    'NO WARNING': '-',
    'NONE': '-',
    'NORMAL': 'Normal',
    'NOT ACT': '-',
    'NOT ACTIVATED': '-',
    'NOT ACTIVE': '-',
    'NOT ARM': '-',
    'NOT AV': '-',
    'NOT CAPABLE': '-',
    'NOT CLS': '-',
    'NOT CODED': '-',
    'NOT COMMAND': '-',
    'NOT DEFINE': '-',
    'NOT DEPLOY': '-',
    'NOT DETECTED': '-',
    'NOT DISC': '-',
    'NOT DISP': '-',
    'NOT DN': '-',
    'NOT DN LKD': '-',
    'NOT EN': '-',
    'NOT ENABLED': '-',
    'NOT ENGA': '-',
    'NOT ENGAGED': '-',
    'NOT EXT': '-',
    'NOT FLASH': '-',
    'NOT FULLY OPEN': 'Closed',
    'NOT KEYED': '-',
    'NOT LIMIT': '-',
    'NOT ON': '-',
    'NOT POP UP': '-',
    'NOT PRES': '-',
    'NOT RA': '-',
    'NOT SCAN': '-',
    'NOT SELECTED': '-',
    'NOT SET': '-',
    'NOT STOWED': '-',
    'NOT TA': '-',
    'NOT UPLOCKED': '-',
    'NOT USED': '-',
    'NOT': '-',
    'NOTACT': '-',
    'NOTARM': '-',
    'NOTINTRNS': '-',
    'Neutral/Down': 'Down',
    'Neutral/Up': 'Up',
    'No': '-',
    'No Adv': '-',
    'No Advisory': '-',
    'No Caution': '-',
    'No Cautn': '-',
    'No Comm': '-',
    'No Discrepancy': '-',
    'No Dn Advisory': '-',
    'No Event': '-',
    'No Fail': '-',
    'No Fault': '-',
    'No Fire': '-',
    'No Firef': '-',
    'No Jam': '-',
    'No Leak': '-',
    'No Overspeed': '-',
    'No RA Dangerous': '-',
    'No Sel': '-',
    'No Smoke': '-',
    'No Stall': '-',
    'No TA Dangerous': '-',
    'No TA Only': '-',
    'No Warn': '-',
    'No Warning': '-',
    'No alert': '-',
    'No caution': '-',
    'No fail': '-',
    'No ice': '-',
    'No warning': '-',
    'None': '-',
    'Not': '-',
    'Not Abv IDLE': '-',
    'Not Activated': '-',
    'Not Active': '-',
    'Not Active/Installed': '-',
    'Not Arm': '-',
    'Not Armed': '-',
    'Not Avail': '-',
    'Not Checked': '-',
    'Not Clear': '-',
    'Not Closed': 'Open',
    'Not Cmd': '-',
    'Not Confirmed': '-',
    'Not Decl': '-',
    'Not Deployed': '-',
    'Not Detected': '-',
    'Not Displayed': '-',
    'Not Down': '-',
    'Not Emitting': '-',
    'Not Eng': '-',
    'Not Engaged': '-',
    'Not FWC': '-',
    'Not Gated': '-',
    'Not Install': '-',
    'Not Installed': '-',
    'Not Low': '-',
    'Not Man': '-',
    'Not Normal': '-',
    'Not Open': 'Closed',
    'Not Over': '-',
    'Not Passing': '-',
    'Not Sel': '-',
    'Not Selected': '-',
    'Not Up': '-',
    'Not Up Locked': '-',
    'Not Valid': '-',
    'Not act': '-',
    'Not active': '-',
    'Not align': '-',
    'Not armed': '-',
    'Not avail': '-',
    'Not availab': '-',
    'Not available': '-',
    'Not capabl': '-',
    'Not capable': '-',
    'Not closed': '-',
    'Not down': '-',
    'Not enabled': '-',
    'Not eng': '-',
    'Not engage': '-',
    'Not engaged': '-',
    'Not fail': '-',
    'Not failed': '-',
    'Not in reversion': '-',
    'Not latched': '-',
    'Not locked': '-',
    'Not oper': '-',
    'Not pulled': '-',
    'Not reverted': '-',
    'Not sel': '-',
    'Not selected': '-',
    'Not start': '-',
    'Not up': '-',
    'Not_oper': '-',
    'Notactived': '-',
    'Non faulted': '-',
    'OFF': 'Off',
    'ON': 'On',
    'ON GROUND': 'Ground',
    'OPEN': 'Open',
    'OPER': 'Engaged',
    'OUT TEMP': '-',
    'OUTER': 'Present',
    'OVHT': 'Overheat',
    'Openned': 'Open',
    'Oper': 'Operational',
    'PART EXT': 'Part Extended',
    'PLAN': 'Plan',
    'POP UP': 'Pop Up',
    'PRESENT': 'Present',
    'PREVENTIVE': 'Preventive',
    'PULL': 'Pulled',
    'PUSH': 'Active',
    'RECORD': 'Record',
    'RED': 'Red',
    'REQUEST': 'Request',
    'RIGHT': 'Right',
    'ROTATE': 'Rotated',
    'RUN': '-',
    'S': 'South',
    'SCANNING': 'Scanning',
    'SELECT': 'Selected',
    'SELECTED': 'Selected',
    'Select On': 'Selected',
    'Selected On': 'Selected',
    'SHAKE': 'Shake',
    'SHUTDOWN': 'Shutdown',
    'SINGLE': 'Single',
    'SMOKE': 'Smoke',
    'STANDBY': 'Standby',
    'STBY': 'Standby',
    'STD': 'Selected',
    'STOWED': 'Stowed',
    'Stall On': 'Stall',
    'Set': 'Engaged',
    'SET': 'Engaged',
    'Switch applied': 'Applied',
    'Switch not applied': '-',
    'TA ONLY': 'TA Only',
    'TEST': 'Test',
    'TILT': 'Tilt',
    'TRANSIT': 'Transit',
    'TRIM': 'Trim',
    'TRIM DN': 'Trim',
    'TRIM UP': 'Trim',
    'TRUE': 'True',
    'UNSTOW': 'Unstowed',
    'UP': 'Up',
    'UP ADV CORRECT': 'Up Advisory Correct',
    'UP+LK': 'Up',
    'UPL': 'Up',
    'UPLOCKED': 'Up',
    'Up Locked': 'Up',
    'UNARMED': '-',
    'UNDEFINED': '-',
    'UNGATED': '-',
    'Ungated': '-',
    'UNIQUE': 'Unique',
    'UNLOCKED': 'Unlocked',
    'UNSCHED': 'Unscheduled',
    'VALID': 'Valid',
    'VMO ENGA': 'Engaged',
    'Vmo/Mmo Warning': 'Warning',
    'W': 'West',
    'WARN': 'Warning',
    'WARNING': 'Warning',
    'WOW': 'Ground',
    'Warning Off': '-',
    'Warning On': 'Warning',
    'Windshear Detecte': 'Warning',
    'available': 'Available',
    'climb': 'Climb',
    'connected': 'Connected',
    'displayed': 'Displayed',
    'down': 'Down',
    'engaged': 'Engaged',
    'false': 'False',
    'fault': 'Fault',
    'heading': 'Heading',
    'keyed': 'Keyed',
    'n/a': '-',
    'no Fault': '-',
    'no fault': '-',
    'no caution': '-',
    'no marker': '-',
    'no warning': '-',
    'none': '-',
    'not Healthy': '-',
    'not armed': '-',
    'not available': '-',
    'not beta': '-',
    'not displayed': '-',
    'not engaged': '-',
    'not feather': '-',
    'not hot': '-',
    'not keyed': '-',
    'not low': '-',
    'not select': '-',
    'not selected': '-',
    'not used': '-',
    'not valid': 'Invalid',
    'off': 'Off',
    'on': 'On',
    'selected': 'Selected',
    'true': 'True',
    'up': 'Up',
    'valid': 'Valid',
}


TRUE_STATES = [
    'APU Bleed Valve not Fully Open',
    'APU Fire',
    'Aft CG',
    'Air',
    'Asymmetrical',
    'CMD Mode',
    'CWS Mode',
    'Deployed',
    'Down',
    'Engaged',
    'Event',
    'FMA Displayed',
    'Fault',
    'Good',
    'Ground',
    'Keyed',
    'Not Armed',
    'On',
    'Open',
    'Selected',
    'Track Phase',
    'Unlocked',
    'Valid',
    'Warning',
]


FALSE_STATES = [
    'APU Bleed Valve Fully Open',
    'Air',
    'Armed',
    'Closed',
    'FMA Not Displayed',
    'Ground',
    'Invalid',
    'No APU Fire',
    'No Aft CG',
    'No Event',
    'No Fault',
    'No Warning',
    'Normal',
    'Not Deployed',
    'Not Engaged',
    'Not Keyed',
    'Not in CMD Mode',
    'Not in CWS Mode',
    'Off',
    'Up',
]


# Examples where states conflict:
# * VMO/MMO Selected


##############################################################################
# Functions


def get_parameter_correction(parameter_name):

    if parameter_name in PARAMETER_CORRECTIONS:
        return PARAMETER_CORRECTIONS[parameter_name]

    for pattern, mapping in PARAMETER_CORRECTIONS.items():
        if wildcard_match(pattern, [parameter_name]):
            return mapping


def normalise_discrete_mapping(original_mapping, parameter_name=None):

    true_state = original_mapping[1]
    false_state = original_mapping[0]

    true_state = STATE_CORRECTIONS.get(true_state, true_state)
    false_state = STATE_CORRECTIONS.get(false_state, false_state)

    inverted = true_state in FALSE_STATES or false_state in TRUE_STATES

    normalised_mapping = \
        get_parameter_correction(parameter_name) if parameter_name else None

    if not normalised_mapping:
        normalised_mapping = {0: false_state, 1: true_state}

    return normalised_mapping, inverted


def normalise_multistate_mapping(original_mapping, parameter_name=None):

    normalised_mapping = \
        get_parameter_correction(parameter_name) if parameter_name else None

    if not normalised_mapping:
        normalised_mapping = {}

        for value, state in original_mapping.items():
            normalised_mapping[value] = STATE_CORRECTIONS.get(state, state)

    return normalised_mapping
