'''
Multi-state Parameter State Value Mappings
'''

from flightdatautilities.patterns import wildcard_match


PARAMETER_CORRECTIONS = {
    '115 VAC Standby Bus': {1: 'On'},
    '115 VAC XFR Bus': {1: 'On'},
    '28 VDC Battery Bus Hot': {1: 'On'},
    '28 VDC Battery Bus Switch Hot': {1: 'On'},
    '28 VDC Battery Bus': {1: 'On'},
    '28 VDC Bus (*)': {1: 'On'},
    '28 VDC Standby Bus': {1: 'On'},
    'AC Bus (*) (*) On': {1: 'On'},
    'AC Bus (*) Status': {1: 'Powered'}, # Multi-state
    'AC Emergency Bus Failure': {1: 'Failed'},
    'AC Essential Bus Failure': {1: 'Failed'},
    'AC Essential Bus': {1: 'On'},
    'ADF (*) Selected (*)': {1: 'Selected'},
    'AP (*) Disconnect': {1: 'Disconnect'},
    'AP (*) Engaged': {1: 'Engaged'},
    'AP Altitude Capture': {1: 'Engaged'},
    'AP Backcourse': {1: 'Engaged'},
    'AP Climb Mode': {1: 'Engaged'},
    'AP Collective Glideslope': {1: 'Armed'},
    'AP Descend Mode': {1: 'Engaged'},
    'AP ILS Localizer': {1: 'Armed'},
    'AP Manual Disconnect': {1: 'Disconnect'},
    'AP Pitch Glideslope': {1: 'Armed'},
    'AP VNAV': {1: 'Engaged'},
    'AP Warning': {1: 'Warning'},
    'APU Bleed Air Switch': {1: 'On'},
    'APU Bleed Valve (*) Open': {1: 'Open', 0: 'Closed'},
    'APU Fire': {1: 'Fire'},
    'APU Oil Press Low': {1: 'Low Press'},
    'APU Oil Temp High': {1: 'High Temp'},
    'APU On': {1: 'On'},
    'AT Engaged': {1: 'Engaged'},
    'AT FMC Speed': {1: 'Engaged'},
    'AT Go Around': {1: 'Engaged'},
    'AT Limit': {1: 'Engaged'},
    'AT MCP Speed': {1: 'Engaged'},
    'AT Manual Disconnect': {1: 'Disconnect'},
    'AT Min Speed': {1: 'Engaged'},
    'AT N1': {1: 'Engaged'},
    'AT Retard': {1: 'Engaged'},
    'AT Warning': {1: 'Warning'},
    'Air Conditioning Mode': {1: 'Normal', 0: 'Economy'},
    'Aiframe De-Icing': {1: 'On'},
    'Airports Selected (*)': {1: 'Selected', 0: 'Not Selected'},
    'Airspeed Increase Alert': {1: 'Alert'},
    'All Engines Operative': {1: 'AEO'},
    'Altitude Acquire Mode Armed': {1: 'Armed'},
    'Altitude Acquire': {1: 'Engaged'},
    'Altitude Alert': {1: 'Alert'},
    'Altitude Hold Push Button Light': {1: 'On'},
    'Altitude Hold': {1: 'Selected'},
    'Altitude Reference Active': {1: 'FMC', 0: 'MCP'},
    'Approach Mode Selected (*)': {1: 'Selected'},
    'Auto Speedbrake Extend': {1: 'Extend'},
    'Autobrake (*) Selected': {1: 'Selected'},
    'Autobrake Applied': {1: 'Autobrake'},
    'Autobrake Selected RTO': {1: 'Selected'},
    'Autoland Enabled': {1: 'Enabled'},
    'Backcourse Engaged': {1: 'Engaged'},
    'Battery (*) Overheat': {1: 'Overheat'},
    'Brake Main Selected': {1: 'Main'},
    'CGB Chip Detector': {1: 'Chip Detected'},
    'Cabin Altitude Warning': {1: 'Warning'},
    'Control Wheel Steering (*) Engaged': {1: 'Engaged'},
    'Control Wheel Steering Pitch Engaged': {1: 'Engaged'},
    'Control Wheel Steering Roll Engaged': {1: 'Engaged'},
    'Cruise Speed Low': {1: 'Low'},
    'DC Bus (*) Status': {1: 'Powered'}, # Multi-state
    'DEU Centre Display Format (*)': {1: 'Selected'},
    'DEU Check List': {1: 'Selected'},
    'DME Source': {1: 'DME'},
    'Degraded Performance Caution': {1: 'Caution'},
    'Dual Input Warning': {1: 'Dual'},
    'Dual Input': {1: 'Dual'},
    'ECS Pack (*) High Flow': {1: 'High'},
    'ECS Pack (*) On': {1: 'On'},
    'EFIS Frame': {1: 'EFIS'},
    'EGB (*) Chip Detector': {1: 'Chip Detected'},
    'EID (*) Submodes Page': {0: 'Status'}, # Multi-state
    'Eng (*) Airborne Vib Monitoring': {1: 'Alert'},
    'Eng (*) Anti Ice Valve Command': {1: 'Command'},
    'Eng (*) Anti Ice': {1: 'On'},
    'Eng (*) Any Running': {1: 'Running'},
    'Eng (*) Bleed': {1: 'Open'},
    'Eng (*) Chip Detector (*)': {1: 'Chip Detected'},
    'Eng (*) Cowl Anti Ice': {1: 'On'},
    'Eng (*) Cutoff': {1: 'Cutoff'},
    'Eng (*) Failure': {1: 'Failed'},
    'Eng (*) Fire (*)': {1: 'Fire'},
    'Eng (*) Fire Extinguish Switch': {1: 'Pulled'},
    'Eng (*) Fire Handle Position (*)': {1: 'Pulled'},
    'Eng (*) Fuel Press Low': {1: 'Low Press'},
    'Eng (*) Hyd (*) Press Low': {1: 'Low Press'},
    'Eng (*) Oil Press Low Red Warning': {1: 'Warning'},
    'Eng (*) Oil Press Low': {1: 'Low Press'},
    'Eng (*) Overheat': {1: 'Overheat'},
    'Eng (*) Overspeed': {1: 'Overspeed'},
    'Eng (*) Pylon Overheat': {1: 'Overheat'},
    'Eng (*) Running': {1: 'Running'},
    'Eng (*) Start Valve': {1: 'Open'},
    'Eng (*) Thrust Reverser (*) Deployed': {1: 'Deployed'},
    'Eng (*) Thrust Reverser (*) In Transit': {1: 'In Transit'},
    'Eng (*) Thrust Reverser (*) Unlocked': {1: 'Unlocked'},
    'Wing Anti Ice': {1: 'On'},
    'Wing Anti Ice Selected On': {1: 'Selected On'},
    'Eng Bleed Open': {1: 'Open', 0: 'Closed'},
    'Event Marker (*)': {1: 'Event'},
    'FCC Local Limited Master': {0 : 'FCC (L)'}, # Multi-state
    'FD (*) Engaged': {1: 'Engaged'},
    'FMC Data Source Selected': {1: 'FMC', 0: 'IRU'},
    'Final Approach Course Engaged': {1: 'Engaged'},
    'Fire APU Dual Bottle System': {1: 'Fire'},
    'Fire APU Single Bottle System': {1: 'Fire'},
    'Flap Alternate Armed': {1: 'Armed'},
    'Flap Leading Edge (*) Extended': {1: 'Extended'},
    'Flap Leading Edge (*) In Transit': {1: 'In Transit'},
    'Flap Load Relief': {1: 'Load Relief'},
    'Flare Engaged': {1: 'Engaged'},
    'Flight Path Vector Selected (*)': {1: 'Selected'},
    'Fuel Qty (*) Low': {1: 'Warning'},
    'Fuel Qty (*) Low': {1: 'Warning'},
    'GNSS Output Correction': {1: 'Corrected'},
    'GPS Active': {1: 'Active'},
    'GPS Approach': {1: 'GPS'},
    'Gear (*) Down (*)': {1: 'Down', 0: 'Up'},
    'Gear (*) Down In Transit': {1: 'Extending'},
    'Gear (*) Locked Down (*)': {1: 'Locked'},
    'Gear (*) On Ground': {1: 'Ground', 0: 'Air'},
    'Gear (*) Red Warning': {1: 'Warning'},
    'Gear (*) Up (*)': {1: 'Up', 0: 'Down'},
    'Gear (*) Up In Transit': {1: 'Retracting'},
    'Gear Down Selected (*)': {1: 'Down', 0: 'Up'},
    'Gear Up Selected (*)': {1: 'Up', 0: 'Down'},
    'Glidepath Engaged': {1: 'Engaged'},
    'Go Around Mode': {1: 'Engaged'},
    'Ground Spoiler (*) Deployed': {1: 'Deployed'},
    'Ground Station Data Selected (*)': {1: 'Selected'},
    'HUD Approach Warning': {1: 'Warning'},
    'HUD Combiner Position': {1: 'Active', 0: 'Stowed'},
    'HUD Touchdown': {1: 'Set'},
    'Heading Engaged': {1: 'Engaged'},
    'Heading Hold': {1: 'Engaged'},
    'Heading Mag-True (*)': {1: 'True', 0: 'Magnetic'},
    'Heading Selected Engaged': {1: 'Engaged'},
    'Heading Up MAP Format (*)': {1: 'Selected'},
    'Hectopascals Selected (*)': {1: 'Selected'},
    'Hyd (*) Electrical Press Low': {1: 'Low Press'},
    'Hyd (*) Flight Controls Press Low': {1: 'Low Press'},
    'Hyd (*) Press Low (*)': {1: 'Low Press'},
    'Hyd Standby Low Press': {1: 'Low Press'},
    'ILS (*) Localizer Engaged': {1: 'Engaged'},
    'ILS (*) Selected': {1: 'Selected'},
    'ILS (*) Standby': {1: 'Standby'},
    'ILS Glideslope Engaged': {1: 'Engaged'},
    'ILS Inner Marker (*)': {1: 'Present'},
    'ILS Middle Marker (*)': {1: 'Present'},
    'ILS Outer Marker (*)': {1: 'Present'},
    'ILS-VOR Selected': {1: 'ILS', 0: 'VOR'},
    'IRU Navigation Capable': {1: 'Capable'},
    'Isolation Valve Open': {1: 'Open'},
    'Key HF (*)': {1: 'Keyed'},
    'Key Satcom (*)': {1: 'Keyed'},
    'Key VHF (*)': {1: 'Keyed'},
    'Land (*) (*)': {1: 'Land'},
    'Landing Configuration Gear Warning': {1: 'Warning'},
    'Landing Configuration Speedbrake Caution': {1: 'Caution'},
    'Leading Edge Master Extended': {1: 'Extended'},
    'Leading Edge Master In Transit': {1: 'In Transit'},
    'MDA Selected (*)': {1: 'Selected'},
    'MFD (*) On (*)': {1: 'On'},
    'Map Mode Selected (*)': {1: 'Selected'},
    'Master Caution (*) (*)': {1: 'Caution'},
    'Master Caution': {1: 'Caution'},
    'Master Warning (*) (*)': {1: 'Warning'},
    'Master Warning': {1: 'Warning'},
    'Meters Selected (*)': {1: 'Selected'},
    'Mode Control Panel Speed (*)': {1: 'Engaged'},
    'NAV Mode Active (*)': {1: 'Active'},
    'One Engine Inoperative': {1: 'OEI'},
    'Overspeed Warning': {1: 'Overspeed'},
    'PFD (*) On (*)': {1: 'On'},
    'PFD Navigation Display Format (*)': {1: 'Selected'},
    'PVD (*) Enabled': {1: 'Enabled'},
    'PVD (*) On': {1: 'On'},
    'Pitch Alternate Law': {1: 'Engaged'},
    'Pitch Direct Law': {1: 'Engaged'},
    'Pitch Normal Law': {1: 'Engaged'},
    'Plan Mode Selected (*)': {1: 'Selected'},
    'Position Data Selected (*)': {1: 'Selected'},
    'Roll Trim Command Wing (*) Down': {1: 'Trim'},
    'Rollout Armed': {1: 'Armed'},
    'Rollout Engaged': {1: 'Engaged'},
    'Rotor Brake Engaged': {1: 'Engaged'},
    'Rotors Running': {1: 'Running'},
    'Route Data Selected (*)': {1: 'Selected'},
    'Single Channel Engaged': {1: 'Engaged'},
    'Slat (*) Extended': {1: 'Extended'},
    'Slat (*) In Transit': {1: 'In Transit'},
    'Slat Alternate Armed': {1: 'Armed'},
    'Slat Master In Transit': {1: 'In Transit'},
    'Smoke (*) (*) Warning': {1: 'Smoke'},
    'Smoke Autonomous VCC Warning': {1: 'Smoke'},
    'Smoke Aux Area (*) Warning': {1: 'Smoke'},
    'Smoke Avionics (*) Warning': {1: 'Smoke'},
    'Smoke Avionics Bulk Warning': {1: 'Smoke'},
    'Smoke BCRC Warning': {1: 'Smoke'},
    'Smoke Baggage Warning': {1: 'Smoke'},
    'Smoke Cabin Rest (*) Warning': {1: 'Smoke'},
    'Smoke Cargo (*) Warning': {1: 'Smoke'},
    'Smoke Cargo Aft (*) Warning': {1: 'Smoke'},
    'Smoke Cargo Fwd (*) Warning': {1: 'Smoke'},
    'Smoke Cargo Lower Aft (*) Warning': {1: 'Smoke'},
    'Smoke Cargo Lower Fwd (*) Warning': {1: 'Smoke'},
    'Smoke Cargo Rest (*) Warning': {1: 'Smoke'},
    'Smoke Cargo Upper Aft (*) Warning': {1: 'Smoke'},
    'Smoke Cargo Upper Fwd (*) Warning': {1: 'Smoke'},
    'Smoke Cargo Warning': {1: 'Smoke'},
    'Smoke IFEC Warning': {1: 'Smoke'},
    'Smoke Lavatory (*) Warning': {1: 'Smoke'},
    'Smoke Lower Deck Stowage Warning': {1: 'Smoke'},
    'Smoke Passenger Broadband (*) Warning': {1: 'Smoke'},
    'Speedbrake Armed': {1: 'Armed'},
    'Speedbrake Deployed (*)': {1: 'Deployed'},
    'Speedbrake Do Not Arm': {1: 'Light On'},
    'Speedbrake Selected': {1: 'Deployed/Cmd Up'},
    'Spoiler (*) (*) Deployed': {1: 'Deployed'},
    'Spoiler Armed (*)': {1: 'Armed'},
    'Stabilizer Manual Trim Down': {1: 'Trim'},
    'Stabilizer Manual Trim Up': {1: 'Trim'},
    'Stable Approach Excluding Eng Thrust': {1: 'Stable'},
    'Stable Approach': {1: 'Stable'},
    'Stall Warning': {1: 'Warning'},
    'Stick Pusher (*)': {1: 'Push'},
    'Stick Pusher': {1: 'Push'},
    'Stick Shaker (*)': {1: 'Shake'},
    'Stick Shaker': {1: 'Shake'},
    'Sync Mode Engaged': {1: 'Engaged'},
    'TAWS (*) Dont Sink': {1: 'Warning'},
    'TAWS (*) Glideslope Cancel': {1: 'Cancel'},
    'TAWS (*) Too Low Gear': {1: 'Warning'},
    'TAWS Alert Recorded': {1: 'Alert'},
    'TAWS Alert': {1: 'Alert'},
    'TAWS Caution Obstacle': {1: 'Caution'},
    'TAWS Caution Terrain': {1: 'Caution'},
    'TAWS Caution': {1: 'Caution'},
    'TAWS Dont Sink': {1: 'Warning'},
    'TAWS Failure': {1: 'Failed'},
    'TAWS General': {1: 'Warning'},
    'TAWS Glideslope': {1: 'Warning'},
    'TAWS Inoperative': {1: 'Warning'},
    'TAWS Minimums': {1: 'Minimums'},
    'TAWS Mode 5': {1: 'Warning'},
    'TAWS Obstacle Caution': {1: 'Caution'},
    'TAWS Obstacle Warning': {1: 'Warning'},
    'TAWS Obstacle': {1: 'Warning'},
    'TAWS Predictive Windshear': {1: 'Warning'},
    'TAWS Pull Up': {1: 'Warning'},
    'TAWS Pull Up': {1: 'Warning'},
    'TAWS Sink Rate': {1: 'Warning'},
    'TAWS Terrain Ahead Pull Up': {1: 'Warning'},
    'TAWS Terrain Ahead': {1: 'Warning'},
    'TAWS Terrain Awareness Inoperative': {1: 'Warning'},
    'TAWS Terrain Awareness Not Available': {1: 'Warning'},
    'TAWS Terrain Caution': {1: 'Caution'},
    'TAWS Terrain Clearance Floor Alert (*)': {1: 'Alert'},
    'TAWS Terrain Display Selected (*)': {1: 'Selected'},
    'TAWS Terrain Override': {1: 'Override'},
    'TAWS Terrain Pull Up': {1: 'Warning'},
    'TAWS Terrain Pull Up Ahead': {1: 'Warning'},
    'TAWS Terrain Pull Up': {1: 'Warning'},
    'TAWS Terrain Warning': {1: 'Warning'},
    'TAWS Terrain': {1: 'Warning'},
    'TAWS Too Low Flap': {1: 'Warning'},
    'TAWS Too Low Gear': {1: 'Warning'},
    'TAWS Too Low Terrain': {1: 'Warning'},
    'TAWS Unspecified': {1: 'Warning'},
    'TAWS V1 Callout Enabled (*)': {1: 'Enabled'},
    'TAWS Warning': {1: 'Warning'},
    'TAWS Windshear Caution (*)': {1: 'Caution'},
    'TAWS Windshear Inoperative': {1: 'Warning'},
    'TAWS Windshear Siren': {1: 'Siren'},
    'TAWS Windshear Warning (*)': {1: 'Warning'},
    'TAWS Windshear': {1: 'Warning'},
    'TCAS (*) Failure': {1: 'Failed'},
    'TCAS Altitude Reporting': {1: 'On'},
    'TCAS Combined Control': {0: 'No Advisory'}, # Multi-state
    'TCAS Down Advisory': {0: 'No Down Advisory'}, # Multi-state
    'TCAS Installed': {1: 'Installed'},
    'TCAS RA (*)': {1: 'RA'},
    'TCAS System Status': {1: 'Failed'},
    'TCAS TA (*)': {1: 'TA'},
    'TCAS Up Advisory': {0: 'No Up Advisory'}, # Multi-state
    'TFC Selected (*)': {1: 'Selected'},
    'Takeoff And Go Around': {1: 'TOGA'},
    'Takeoff Configuration Flap Warning': {1: 'Warning'},
    'Takeoff Configuration Gear Warning': {1: 'Warning'},
    'Takeoff Configuration Parking Brake Warning': {1: 'Warning'},
    'Takeoff Configuration Rudder Warning': {1: 'Warning'},
    'Takeoff Configuration Spoiler Warning': {1: 'Warning'},
    'Takeoff Configuration Stabilizer Warning': {1: 'Warning'},
    'Takeoff Configuration Warning': {1: 'Warning'},
    'Thrust Reversers': {1: 'Deployed'},
    'VOR (*) Selected (*)': {1: 'Selected'},
    'VOR Mode Selected (*)': {1: 'Selected'},
    'VOR-LOC Engaged': {1: 'Engaged'},
    'Vertical Speed Engaged (*)': {1: 'Engaged'},
    'WPT Selected (*)': {1: 'Selected'},
    'WXR Selected (*)': {1: 'Selected'},
    'Wheel Well Fire': {1: 'Fire'},
    'Windshear Caution': {1: 'Caution'},
    'Windshear Warning': {1: 'Warning'},
    'Wing (*) Anti Ice Inboard Valve': {1: 'Open'},
    'Wing (*) Anti Ice Outboard Valve': {1: 'Open'},
    'Wing (*) Anti Ice Valve': {1: 'Open'},
    'Wing (*) Anti Ice': {1: 'On'},
    'Yaw Damper (*) Engaged': {1: 'Engaged'},
    'Yaw Trim (*) Command': {1: 'Trim'},
    'inHg Selected (*)': {1: 'Selected'},


#old list
    #'AP (*) Engaged': {1: 'Engaged'},
    #'APU (*) On': {1: 'On'},
    #'APU Bleed Valve Open': {1: 'Open'},
    #'APU Fire': {1: 'Fire'},
    #'AT Active': {1: 'Activated'},
    #'Alpha Floor': {1: 'Engaged'},
    #'Alternate Law': {1: 'Engaged'},
    #'Altitude Capture Mode': {1: 'Activated'},
    #'Altitude Mode': {1: 'Activated'},
    #'Autobrake Selected RTO': {1: 'Selected'},
    #'Cabin Altitude Warning': {1: 'Warning'},
    #'Climb Mode Active': {1: 'Activated'},
    #'Direct Law': {1: 'Engaged'},
    #'ECS Pack (*) High Flow': {1: 'High', 0: 'Low'},
    #'ECS Pack (*) On': {1: 'On'},
    #'Eng (*) Anti Ice': {1: 'On'},
    #'Eng (*) Bleed': {0: 'Closed', 1: 'Open'},
    #'Eng (*) Fire (1L)': {1: 'Fire'},
    #'Eng (*) Fire (1R)': {1: 'Fire'},
    #'Eng (*) Fire (2L)': {1: 'Fire'},
    #'Eng (*) Fire (2R)': {1: 'Fire'},
    #'Eng (*) Fire': {1: 'Fire'},
    #'Eng (*) Oil Press Low': {1: 'Low Press'},
    #'Eng (*) Thrust Reverser (*) Deployed': {1: 'Deployed'},
    #'Eng (*) Thrust Reverser (*) In Transit': {1: 'In Transit'},
    #'Eng (*) Thrust Reverser (*) Unlocked': {1: 'Unlocked'},
    #'Event Marker (*)': {1: 'Event'},
    #'Event Marker (Capt)': {1: 'Event'},
    #'Event Marker (FO)': {1: 'Event'},
    #'Event Marker': {1: 'Event'},
    #'Expedite Climb Mode': {1: 'Activated'},
    #'Expedite Descent Mode': {1: 'Activated'},
    #'Fire APU Dual Bottle System': {1: 'Fire'},
    #'Fire APU Single Bottle System': {1: 'Fire'},
    #'Flap Alternate Armed': {1: 'Armed'},
    #'Flap Load Relief': {0: 'Normal', 1: 'Load Relief'},
    #'Flare Mode': {1: 'Engaged'},
    #'Fuel Jettison Nozzle': {1: 'Disagree'},
    #'Fuel Qty (L) Low': {1: 'Warning'},
    #'Fuel Qty (R) Low': {1: 'Warning'},
    #'Fuel Qty Low': {1: 'Warning'},
    #'Gear (*) Down': {0: 'Up', 1: 'Down'},
    #'Gear (*) In Air': {0: 'Ground', 1: 'Air'},
    #'Gear (*) In Transit': {1: 'In Transit'},
    #'Gear (*) On Ground': {0: 'Air', 1: 'Ground'},
    #'Gear (*) Red Warning': {1: 'Warning'},
    #'Gear (*) Up': {0: 'Down', 1: 'Up'},
    #'Gear Down Selected': {0: 'Up', 1: 'Down'},
    #'Gear Up Selected': {0: 'Down', 1: 'Up'},
    #'Heading Mode Active': {1: 'Activated'},
    #'ILS Glideslope Capture Active': {1: 'Activated'},
    #'ILS Inner Marker (*)': {1: 'Present'},
    #'ILS Localizer Capture Active': {1: 'Activated'},
    #'ILS Localizer Track Active': {1: 'Activated'},
    #'ILS Middle Marker (*)': {1: 'Present'},
    #'ILS Outer Marker (*)': {1: 'Present'},
    #'Jettison Nozzle': {1: 'Jettison'},
    #'Key HF (*)': {1: 'Keyed'},
    #'Key Satcom (*)': {1: 'Keyed'},
    #'Key VHF (*) (*)': {1: 'Keyed'},
    #'Land Track Activated': {1: 'Activated'},
    #'Landing Configuration Gear Warning': {1: 'Warning'},
    #'Landing Configuration Speedbrake Caution': {1: 'Caution'},
    #'Master Caution (*)': {1: 'Caution'},
    #'Master Warning (*)': {1: 'Warning'},
    #'NAV Mode Active': {1: 'Activated'},
    #'Normal Law': {1: 'Engaged'},
    #'Open Climb Mode': {1: 'Activated'},
    #'Open Descent Mode': {1: 'Activated'},
    #'Overspeed Warning': {1: 'Overspeed'},
    #'Pitch Alternate Law (*)': {1: 'Engaged'},
    #'Pitch Direct Law': {1: 'Engaged'},
    #'Pitch Normal Law': {1: 'Engaged'},
    #'Roll Alternate Law': {1: 'Engaged'},
    #'Roll Direct Law': {1: 'Engaged'},
    #'Roll Go Around Mode Active': {1: 'Activated'},
    #'Roll Normal Law': {1: 'Engaged'},
    #'Runway Mode Active': {1: 'Activated'},
    #'Slat Alternate Armed': {1: 'Armed'},
    #'Speed Control (*) Auto': {1: 'Auto'},
    #'Speed Control (*) Manual': {0: 'Auto'},
    #'Speedbrake Armed': {1: 'Armed'},
    #'Speedbrake Deployed': {1: 'Deployed'},
    #'Spoiler (*) Deployed': {1: 'Deployed'},
    #'Spoiler (*) Outboard Deployed': {1: 'Deployed'},
    #'Stick Pusher (*)': {1: 'Push'},
    #'Stick Shaker (*)': {1: 'Shake'},
    #'TAWS (*) Dont Sink': {1: 'Warning'},
    #'TAWS (*) Glideslope Cancel': {1: 'Cancel'},
    #'TAWS (*) Too Low Gear': {1: 'Warning'},
    #'TAWS Alert': {1: 'Alert'},
    #'TAWS Caution Obstacle': {1: 'Caution'},
    #'TAWS Caution Terrain': {1: 'Caution'},
    #'TAWS Caution': {1: 'Caution'},
    #'TAWS Failure': {1: 'Failed'},
    #'TAWS Glideslope': {1: 'Warning'},
    #'TAWS Minimums': {1: 'Minimums'},
    #'TAWS Obstacle Warning': {1: 'Warning'},
    #'TAWS Predictive Windshear': {1: 'Warning'},
    #'TAWS Pull Up': {1: 'Warning'},
    #'TAWS Sink Rate': {1: 'Warning'},
    #'TAWS Terrain Ahead Pull Up': {1: 'Warning'},
    #'TAWS Terrain Ahead': {1: 'Warning'},
    #'TAWS Terrain Caution': {1: 'Caution'},
    #'TAWS Terrain Override': {1: 'Override'},
    #'TAWS Terrain Pull Up': {1: 'Warning'},
    #'TAWS Terrain Warning Amber': {1: 'Warning'},
    #'TAWS Terrain Warning Red': {1: 'Warning'},
    #'TAWS Terrain': {1: 'Warning'},
    #'TAWS Too Low Flap': {1: 'Warning'},
    #'TAWS Too Low Terrain': {1: 'Warning'},
    #'TAWS Warning': {1: 'Warning'},
    #'TAWS Windshear Caution': {1: 'Caution'},
    #'TAWS Windshear Siren': {1: 'Siren'},
    #'TAWS Windshear Warning': {1: 'Warning'},
    #'TCAS (*) Failure': {1: 'Failed'},
    #'TCAS RA': {1: 'RA'},
    #'TCAS TA': {1: 'TA'},
    #'Takeoff And Go Around': {1: 'TOGA'},
    #'Takeoff Configuration AP Warning': {1: 'Warning'},
    #'Takeoff Configuration Aileron Warning': {1: 'Warning'},
    #'Takeoff Configuration Flap Warning': {1: 'Warning'},
    #'Takeoff Configuration Gear Warning': {1: 'Warning'},
    #'Takeoff Configuration Parking Brake Warning': {1: 'Warning'},
    #'Takeoff Configuration Rudder Warning': {1: 'Warning'},
    #'Takeoff Configuration Spoiler Warning': {1: 'Warning'},
    #'Takeoff Configuration Stabilizer Warning': {1: 'Warning'},
    #'Takeoff Configuration Warning': {1: 'Warning'},
    #'Thrust Mode Selected (*)': {1: 'Selected'},
    #'Wing Anti Ice': {1: 'On'},

}


STATE_CORRECTIONS = {
    '': '-',
    '*': '-',
    '.': '-',
    '..': '-',
    '...': '-',
    '....': '-',
    '.....': '-',
    '......': '-',
    '--': '-',
    '---': '-',
    '----': '-',
    '-----': '-',
    '------': '-',
    '-------': '-',
    '--------': '-',
    '---------': '-',
    '----------': '-',
    '<None>': '-',
    'A/P DISC': 'Warning',
    'ABOVE': 'Above',
    'ACTIVATED': 'Active',
    'ACTIVE': 'Active',
    'ACTIVED': 'Active',
    'AIR': 'Air',
    'ALERT': 'Alert',
    'ALERT A': 'Alert',
    'ALL': 'All',
    'ALTITUDE LOST': 'Altitude Lost',
    'ALTN': 'Alternate',
    'AMBER': 'Amber',
    'ANY': 'Any',
    'APPLIED': 'Applied',
    'APPR ENGA': 'Engaged',
    'APU Bleed Valve Fully Open': 'Open',
    'APU Bleed Valve not Fully Open': 'Closed',
    'ARMED': 'Armed',
    'ASYM': 'Assymetrical',
    'AUTO': 'Auto',
    'AUTOMATIC': 'Auto',
    'AVAIL': 'Available',
    'AVAILABLE': 'Available',
    'Actived': 'Activated',
    'Att': 'Attitude',
    'BELOW': 'Below',
    'BETA RANGE': 'Beta',
    'BUS OFF': 'Off',
    'BUS ON': 'On',
    'BYPASS': 'Bypass',
    'CAPABLE': 'Capable',
    'CAPTION OFF': '-',
    'CAPTION ON': 'Engaged',
    'CAUTION': 'Caution',
    'CODED': 'Coded',
    'CLEAR OF CONFLT': 'Clear of Conflict',
    'Cg Warning': 'Warning',
    'CLOSED': 'Closed',
    'CMD Mode': 'Engaged',
    'COMMANDED': 'Deployed',
    'CUTOFF': 'Cutoff',
    'CWS Mode': 'Engaged',
    'DEPLOY': 'Deployed',
    'DEPLOYED': 'Deployed',
    'DETECT': 'Detected',
    'DETECTED': 'Detected',
    'DISABLE': 'Disabled',
    'DISABLED': 'Disabled',
    'DISAGREE': 'Disagree',
    'DISCHARGE': 'Discharge',
    #'DISCONNECT': '-', # Cpnflicting
    'DISCR\'Y': 'Discrepency',
    'DISCONNECT': 'Disconnect',
    'DISENGAGED': '-',
    'DL': 'Down',
    'DISPLAYED': 'Displayed',
    'Diseng': '-',
    'Disp': 'Displayed',
    'Display Off': '-',
    'Display On': 'On',
    'DN+LK': 'Down',
    'DOWN': 'Down',
    'DOWN ADV CORRECT': 'Down Advisory Correct',
    'DOWNLOCKED': 'Down',
    'Down Lock': 'Down',
    'DROP TRACK': 'Drop Track',
    'DUAL': 'Dual',
    'E': 'East',
    'EMIT': 'Keyed',
    'ENABLE': 'Enabled',
    'ENABLED': 'Enabled',
    'ENGA NOT': '-',
    'ENGAGE': 'Engaged',
    'ENGAGED': 'Engaged',
    'EVENT': 'Event',
    'EXTEND': 'Extended',
    'Emitting': 'Keyed',
    'FAIL': 'Fail',
    'FAIL DETEC': 'Fail',
    'FAILURE': 'Fail',
    'FALSE': '-',
    'FAULT': 'Fault',
    'FAULT(S)': 'Fault',
    'FEATHERED': 'Feathered',
    'Falso': '-',
    'Fethr': 'Feathered',
    'FIRE': 'Fire',
    'FLASHED': 'Flashed',
    'FLIGHT': 'Air',
    'FULL EXT': 'Full Extended',
    'FTHRD': 'Feathered',
    'FULL EXT': 'Full Extended',
    'GND': 'Ground',
    'GROUND': 'Ground',
    'HI PRESS': 'High Press',
    'HIGH SPEED': 'High',
    'HIGH TEMP': 'High Temp',
    'HOT': 'Hot',
    'High press': 'High Press',
    'INHIBIT': 'Inhibit',
    'INNER': 'Present',
    'INOP': 'Inoperable',
    'INTRANSIT': 'In Transit',
    'ISOL': 'Isolated',
    'Ignit off': '-',
    'Ignit on': 'On',
    'Inop': 'Inoperable',
    'KEYED': 'Keyed',
    'LEFT': 'Left',
    'LIMIT': 'Limit',
    'LOCKED': 'Locked',
    'LOCKOUT': 'Lockout',
    'LO PRESS': 'Low Press',
    'LOPRESS': 'Low Press',
    'LOPRESS': 'Low Press',
    'LOW PRESS': 'Low Press',
    'LOW SPEED': 'Low',
    'LOW QTY': 'Low',
    'Low Pressure': 'Low Press',
    'LVL CHG': 'Level Change',
    'Low press': 'Low Press',
    'Low prsure': 'Low Press',
    'MACH ENGA': 'Engaged',
    'MAG': 'Magnetic',
    'MAXIMUM': 'Maximum',
    'MMO ENGA': 'Engaged',
    'MID EXT': 'Mid Extended',
    'MIDDLE': 'Present',
    'MODE FAIL': 'Fault',
    'N': 'North',
    'N/UNIQ': '-',
    'NDL': '-',
    'Nfc': 'Not Fully Closed',
    'Nfo': 'Not Fully Open',
    'NO': '-',
    'NO ADVISORY': 'No Advisory',
    'NO COOLING': 'No Cooling',
    'NO DISP': '-',
    'NO INHIBIT': '-',
    'NO RQST': '-',
    'NO FIRE': '-',
    'NO LVL CHG': '-',
    'NO MODE FL': '-',
    'NO SHAKE': '-',
    'NO TEST': '-',
    'NO TRIM': '-',
    'NO WARN': '-',
    'NO WARNING': '-',
    'NONE': '-',
    'NORMAL': 'Normal',
    'NOT ACT': '-',
    'NOT ACTIVATED': '-',
    'NOT ACTIVE': '-',
    'NOT ARM': '-',
    'NOT AV': '-',
    'NOT CAPABLE': '-',
    'NOT CLS': '-',
    'NOT CODED': '-',
    'NOT COMMAND': '-',
    'NOT DEFINE': '-',
    'NOT DEPLOY': '-',
    'NOT DETECTED': '-',
    'NOT DISC': '-',
    'NOT DISP': '-',
    'NOT DN': '-',
    'NOT DN LKD': '-',
    'NOT EN': '-',
    'NOT ENABLED': '-',
    'NOT ENGA': '-',
    'NOT ENGAGED': '-',
    'NOT EXT': '-',
    'NOT FLASH': '-',
    'NOT FULLY OPEN': 'Closed',
    'NOT KEYED': '-',
    'NOT LIMIT': '-',
    'NOT ON': '-',
    'NOT POP UP': '-',
    'NOT PRES': '-',
    'NOT RA': '-',
    'NOT SCAN': '-',
    'NOT SELECTED': '-',
    'NOT SET': '-',
    'NOT STOWED': '-',
    'NOT TA': '-',
    'NOT UPLOCKED': '-',
    'NOT USED': '-',
    'NOT': '-',
    'NOTACT': '-',
    'NOTARM': '-',
    'NOTINTRNS': '-',
    'Neutral/Down': 'Down',
    'Neutral/Up': 'Up',
    'No': '-',
    'No Adv': '-',
    'No Advisory': '-',
    'No Caution': '-',
    'No Cautn': '-',
    'No Comm': '-',
    'No Discrepancy': '-',
    'No Dn Advisory': '-',
    'No Event': '-',
    'No Fail': '-',
    'No Fault': '-',
    'No Fire': '-',
    'No Firef': '-',
    'No Jam': '-',
    'No Leak': '-',
    'No Overspeed': '-',
    'No RA Dangerous': '-',
    'No Sel': '-',
    'No Smoke': '-',
    'No Stall': '-',
    'No TA Dangerous': '-',
    'No TA Only': '-',
    'No Warn': '-',
    'No Warning': '-',
    'No alert': '-',
    'No caution': '-',
    'No fail': '-',
    'No ice': '-',
    'No warning': '-',
    'None': '-',
    'Not': '-',
    'Not Abv IDLE': '-',
    'Not Activated': '-',
    'Not Active': '-',
    'Not Active/Installed': '-',
    'Not Arm': '-',
    'Not Armed': '-',
    'Not Avail': '-',
    'Not Checked': '-',
    'Not Clear': '-',
    'Not Closed': 'Open',
    'Not Cmd': '-',
    'Not Confirmed': '-',
    'Not Decl': '-',
    'Not Deployed': '-',
    'Not Detected': '-',
    'Not Displayed': '-',
    'Not Down': '-',
    'Not Emitting': '-',
    'Not Eng': '-',
    'Not Engaged': '-',
    'Not FWC': '-',
    'Not Gated': '-',
    'Not Install': '-',
    'Not Installed': '-',
    'Not Low': '-',
    'Not Man': '-',
    'Not Normal': '-',
    'Not Open': 'Closed',
    'Not Over': '-',
    'Not Passing': '-',
    'Not Sel': '-',
    'Not Selected': '-',
    'Not Up': '-',
    'Not Up Locked': '-',
    'Not Valid': '-',
    'Not act': '-',
    'Not active': '-',
    'Not align': '-',
    'Not armed': '-',
    'Not avail': '-',
    'Not availab': '-',
    'Not available': '-',
    'Not capabl': '-',
    'Not capable': '-',
    'Not closed': '-',
    'Not down': '-',
    'Not enabled': '-',
    'Not eng': '-',
    'Not engage': '-',
    'Not engaged': '-',
    'Not fail': '-',
    'Not failed': '-',
    'Not in reversion': '-',
    'Not latched': '-',
    'Not locked': '-',
    'Not oper': '-',
    'Not pulled': '-',
    'Not reverted': '-',
    'Not sel': '-',
    'Not selected': '-',
    'Not start': '-',
    'Not up': '-',
    'Not_oper': '-',
    'Notactived': '-',
    'Non faulted': '-',
    'OFF': 'Off',
    'ON': 'On',
    'ON GROUND': 'Ground',
    'OPEN': 'Open',
    'OPER': 'Engaged',
    'OUT TEMP': '-',
    'OUTER': 'Present',
    'OVHT': 'Overheat',
    'Openned': 'Open',
    'Oper': 'Operational',
    'PART EXT': 'Part Extended',
    'PLAN': 'Plan',
    'POP UP': 'Pop Up',
    'PRESENT': 'Present',
    'PREVENTIVE': 'Preventive',
    'PULL': 'Pulled',
    'PUSH': 'Active',
    'RECORD': 'Record',
    'RED': 'Red',
    'REQUEST': 'Request',
    'RIGHT': 'Right',
    'ROTATE': 'Rotated',
    'RUN': '-',
    'S': 'South',
    'SCANNING': 'Scanning',
    'SELECT': 'Selected',
    'SELECTED': 'Selected',
    'Select On': 'Selected',
    'Selected On': 'Selected',
    'SHAKE': 'Shake',
    'SHUTDOWN': 'Shutdown',
    'SINGLE': 'Single',
    'SMOKE': 'Smoke',
    'STANDBY': 'Standby',
    'STBY': 'Standby',
    'STD': 'Selected',
    'STOWED': 'Stowed',
    'Stall On': 'Stall',
    'Set': 'Engaged',
    'SET': 'Engaged',
    'Switch applied': 'Applied',
    'Switch not applied': '-',
    'TA ONLY': 'TA Only',
    'TEST': 'Test',
    'TILT': 'Tilt',
    'TRANSIT': 'Transit',
    'TRIM': 'Trim',
    'TRIM DN': 'Trim',
    'TRIM UP': 'Trim',
    'TRUE': 'True',
    'UNSTOW': 'Unstowed',
    'UP': 'Up',
    'UP ADV CORRECT': 'Up Advisory Correct',
    'UP+LK': 'Up',
    'UPL': 'Up',
    'UPLOCKED': 'Up',
    'Up Locked': 'Up',
    'UNARMED': '-',
    'UNDEFINED': '-',
    'UNGATED': '-',
    'Ungated': '-',
    'UNIQUE': 'Unique',
    'UNLOCKED': 'Unlocked',
    'UNSCHED': 'Unscheduled',
    'VALID': 'Valid',
    'VMO ENGA': 'Engaged',
    'Vmo/Mmo Warning': 'Warning',
    'W': 'West',
    'WARN': 'Warning',
    'WARNING': 'Warning',
    'WOW': 'Ground',
    'Warning Off': '-',
    'Warning On': 'Warning',
    'Windshear Detecte': 'Warning',
    'available': 'Available',
    'climb': 'Climb',
    'connected': 'Connected',
    'displayed': 'Displayed',
    'down': 'Down',
    'engaged': 'Engaged',
    'false': 'False',
    'fault': 'Fault',
    'heading': 'Heading',
    'keyed': 'Keyed',
    'n/a': '-',
    'no Fault': '-',
    'no fault': '-',
    'no caution': '-',
    'no marker': '-',
    'no warning': '-',
    'none': '-',
    'not Healthy': '-',
    'not armed': '-',
    'not available': '-',
    'not beta': '-',
    'not displayed': '-',
    'not engaged': '-',
    'not feather': '-',
    'not hot': '-',
    'not keyed': '-',
    'not low': '-',
    'not select': '-',
    'not selected': '-',
    'not used': '-',
    'not valid': 'Invalid',
    'off': 'Off',
    'on': 'On',
    'selected': 'Selected',
    'true': 'True',
    'up': 'Up',
    'valid': 'Valid',
}


TRUE_STATES = [
    'APU Bleed Valve not Fully Open',
    'APU Fire',
    'Aft CG',
    'Air',
    'Asymmetrical',
    'CMD Mode',
    'CWS Mode',
    'Deployed',
    'Down',
    'Engaged',
    'Event',
    'FMA Displayed',
    'Fault',
    'Good',
    'Ground',
    'Keyed',
    'Not Armed',
    'On',
    'Open',
    'Selected',
    'Track Phase',
    'Unlocked',
    'Valid',
    'Warning',
]


FALSE_STATES = [
    'APU Bleed Valve Fully Open',
    'Air',
    'Armed',
    'Closed',
    'FMA Not Displayed',
    'Ground',
    'Invalid',
    'No APU Fire',
    'No Aft CG',
    'No Event',
    'No Fault',
    'No Warning',
    'Normal',
    'Not Deployed',
    'Not Engaged',
    'Not Keyed',
    'Not in CMD Mode',
    'Not in CWS Mode',
    'Off',
    'Up',
]


# Examples where states conflict:
# * VMO/MMO Selected


##############################################################################
# Functions


def get_parameter_correction(parameter_name):

    if parameter_name in PARAMETER_CORRECTIONS:
        return PARAMETER_CORRECTIONS[parameter_name]

    for pattern, mapping in PARAMETER_CORRECTIONS.items():
        if wildcard_match(pattern, [parameter_name]):
            return mapping


def normalise_discrete_mapping(original_mapping, parameter_name=None):

    true_state = original_mapping[1]
    false_state = original_mapping[0]

    true_state = STATE_CORRECTIONS.get(true_state, true_state)
    false_state = STATE_CORRECTIONS.get(false_state, false_state)

    inverted = true_state in FALSE_STATES or false_state in TRUE_STATES

    normalised_mapping = \
        get_parameter_correction(parameter_name) if parameter_name else None

    if not normalised_mapping:
        normalised_mapping = {0: false_state, 1: true_state}

    return normalised_mapping, inverted


def normalise_multistate_mapping(original_mapping, parameter_name=None):

    normalised_mapping = \
        get_parameter_correction(parameter_name) if parameter_name else None

    if not normalised_mapping:
        normalised_mapping = {}

        for value, state in original_mapping.items():
            normalised_mapping[value] = STATE_CORRECTIONS.get(state, state)

    return normalised_mapping
